name: AWS Terraform Apply
description: Terraform apply for AWS infra

inputs:
  aws-access-key-id:
    description: >-
      AWS Access Key ID. This input is required if running in the GitHub hosted environment.
    required: true
  aws-secret-access-key:
    description: >-
      AWS Secret Access Key. This input is required if running in the GitHub hosted environment.
    required: true
  aws-region:
    description: 'AWS Region, e.g. eu-central-1'
    required: true
  terraform-version:
    description: Terraform version to use
    required: false
    default: 1.10.3
  terraform-directory:
    description: Directory where Terraform config is located
    required: false
    default: '.'
  environment:
    description: The Cloud Environment to run
    required: true

runs:
  using: composite
  steps:
    - name: Terraform Plan
      uses: ./.github/actions/terraform-plan
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        terraform-version: ${{ inputs.terraform-version }}
        terraform-directory: ${{ inputs.terraform-directory }}
        environment: ${{ inputs.environment }}

    - name: Terraform Apply
      id: tfapply
      working-directory: ${{ inputs.terraform-directory }}
      shell: bash
      run: terraform apply -no-color -auto-approve github-actions.tfplan

    - name: Display TF plan
      if: steps.tfapply.outputs.exitcode == 0
      run: |
        echo "### Terraform Apply on ${{ inputs.environment }} from $GITHUB_REF_NAME :rocket:" >> $GITHUB_STEP_SUMMARY
        echo '~~~' >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.tfapply.outputs.stdout }}" >> $GITHUB_STEP_SUMMARY
        echo '~~~' >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Display TF error on summary
      if: steps.tfapply.outputs.exitcode != 0
      run: |
        echo "### Terraform ERROR on ${{ inputs.environment }} from $GITHUB_REF_NAME :rocket:" >> $GITHUB_STEP_SUMMARY
        echo '~~~' >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.tfapply.outputs.stderr }}" >> $GITHUB_STEP_SUMMARY
        echo '~~~' >> $GITHUB_STEP_SUMMARY
        exit ${{ steps.tfapply.outputs.exitcode }}
      shell: bash
