name: "Configure AWS & Resolve Cluster"
description: "Validate credentials, resolve AWS region & EKS cluster, and configure AWS access."

inputs:
  aws-access-key-id:
    description: "AWS access key ID"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key"
    required: true
  aws-region:
    description: "AWS region (optional)"
    required: false
  cluster-name:
    description: "EKS cluster name (optional)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Validate AWS credentials presence
      shell: bash
      run: |
        test -n "${{ inputs.aws-access-key-id }}" || { echo "::error::Missing AWS_ACCESS_KEY_ID"; exit 1; }
        test -n "${{ inputs.aws-secret-access-key }}" || { echo "::error::Missing AWS_SECRET_ACCESS_KEY"; exit 1; }

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}